<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>erp-doctor</ToolCommandName>
    <PackageId>ErpDoctor.Tool</PackageId>
    <Version>0.2.0-alpha.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ErpDoctor.Core\ErpDoctor.Core.csproj" />
    <ProjectReference Include="..\ErpDoctor.Infrastructure\ErpDoctor.Infrastructure.csproj" />
    <ProjectReference Include="..\ErpDoctor.Reporting\ErpDoctor.Reporting.csproj" />
  </ItemGroup>
</Project>
